version: 2
jobs:
  test-linux:
    docker:
      - image: antoniogamiz/documentable-testing
    steps:
      - checkout
      - run:
          name: Test Raku Documentable
          command: |
            zef update
            zef install .
workflows:
  version: 2
  test-deploy:
    jobs:
      - test-linux
