version: 2

variables:
  linux: &linux
    machine: true
  install-rakudo: &install-rakudo
    run:
      name: Build and install rakudo
      command: |
        git clone https://github.com/rakudo/rakudo.git $HOME/rakudo
        cd $HOME/rakudo
        perl Configure.pl --gen-moar --gen-nqp --make-install
  install-dependencies: &install-dependencies
    run:
      name: Install dependencies
      command: |
        ZEF_BUILD="/home/circleci/rakudo/install/share/perl6/site/bin"
        git clone https://github.com/ugexe/zef.git && cd zef && perl6 -Ilib bin/zef install .
  test-documentable: &test-documentable
    run:
      name: Run tests
      command: |
        zef install .

        # test one build
        git clone https://github.com/antoniogamiz/mini-doc
        cd mini-doc
        documentable setup
        documentable start --topdir=test-doc -v -a
jobs:
  test-linux:
    <<: *linux
    environment:
      PATH: /home/circleci/rakudo/install/share/perl6/site/bin:/home/circleci/rakudo/install/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    steps:
      - checkout
      - *install-rakudo
      - *install-dependencies
      - *test-documentable

workflows:
  version: 2
  test:
    jobs:
      - test-linux
